export const TechStack = [
    {
        name: "HTML",
        group: "FrontEnd",
        imageURL: "/Technologies/html.png",
        alt: "HTML Logo",
    },
    {
        name: "CSS",
        group: "FrontEnd",
        imageURL: "/Technologies/css3.png",
        alt: "CSS Logo",
    },
    {
        name: "JavaScript",
        group: "FrontEnd",
        imageURL: "/Technologies/javascript.png",
        alt: "JavaScript Logo",
    },
    {
        name: "Tailwind",
        group: "FrontEnd",
        imageURL: "/Technologies/tailwind.png",
        alt: "Tailwind CSS Logo",
    },
    {
        name: "Bootstrap",
        group: "FrontEnd",
        imageURL: "/Technologies/bootstrap.png",
        alt: "Bootstrap Logo",
    },
    {
        name: "React",
        group: "FrontEnd",
        imageURL: "/Technologies/react.png",
        alt: "React Logo",
    },
    {
        name: "Next.js",
        group: "FrontEnd",
        imageURL: "/Technologies/nextjs.png",
        alt: "Next.js Logo",
    },
    {
        name: "Astro",
        group: "FrontEnd",
        imageURL: "/Technologies/astro.png",
        alt: "Astro Logo",
    },
    {
        name: "Node.js",
        group: "BackEnd",
        imageURL: "/Technologies/nodejs.png",
        alt: "Node.js Logo",
    },
    {
        name: "Express",
        group: "BackEnd",
        imageURL: "/Technologies/express.png",
        alt: "Express Logo",
    },
    {
        name: "Python",
        group: "BackEnd",
        imageURL: "/Technologies/python.png",
        alt: "Python Logo",
    },
    {
        name: "Express Middlewares",
        group: "BackEnd",
        imageURL: "/Technologies/express-middlewares.png",
        alt: "Express Middlewares Logo",
    },
    {
        name: "MySQL",
        group: "BackEnd",
        imageURL: "/Technologies/mysql.png",
        alt: "MySQL Logo",
    },
    {
        name: "PostgreSQL",
        group: "BackEnd",
        imageURL: "/Technologies/postgresql.png",
        alt: "PostgreSQL Logo",
    },
    {
        name: "MariaDB",
        group: "BackEnd",
        imageURL: "/Technologies/mariadb.png",
        alt: "MariaDB Logo",
    },
    {
        name: "SQLite",
        group: "BackEnd",
        imageURL: "/Technologies/sqlite.png",
        alt: "SQLite Logo",
    },
    {
        name: "C/C++",
        group: "General Programming",
        imageURL: "/Technologies/cplusplus.png",
        alt: "C/C++ Logo",
    },
    {
        name: "Java",
        group: "General Programming",
        imageURL: "/Technologies/java.png",
        alt: "Java Logo",
    },
    {
        name: "Haskell",
        group: "General Programming",
        imageURL: "/Technologies/haskell.png",
        alt: "Haskell Logo",
    },
    {
        name: "Prolog",
        group: "General Programming",
        imageURL: "/Technologies/prolog.png",
        alt: "Prolog Logo",
    },
];
